### ISSUE TITLE
Memory allocation inefficient for large arrays

### ISSUE THREAD

**Issue by vchuravy** [JuliaGPU/CuArrays.jl#152]
IIUC correctly we are currently using a next power of two pooling scheme.

```
poolidx(n) = ceil(Int, log2(n))+1
poolsize(idx) = 2^(idx-1)
```

So in the worst case 

```
using CuArrays
N = 2^30
mem = N * sizeof(Float64) / 1024^3 # 8 GB
@show mem
CuArrays.@time CuArray{Float64}(N+1)
```
`CUDA error: out of memory (code #2, ERROR_OUT_OF_MEMORY)`
Even though I have 15GB of memory free on that GPU

Even more amusing

```
using CuArrays
N = 2^29
mem = N * sizeof(Float64) / 1024^3 # 4 GB
@show mem
CuArrays.@time CuArray{Float64}(N+1)
```

```
  7.249061 seconds (1.02 M CPU allocations: 51.781 MiB, 1.16% gc time) (1 GPU allocation: 4.000 GiB, 94.56% gc time of which 100.00% spent allocating)
```

Even though `nvidia-smi` reports ~8GB used
```
|    0     40082      C   ...ition1/llgrid/pkg/julia-1.0.0/bin/julia  9360MiB |
```
and allocating a second time fails.

cc: @denizyuret

**Comment by ekinakyurek** [comment]
Possible solution is using different scheme for small and large arrays as is [here](https://github.com/pytorch/pytorch/blob/543d4af79fcdec2210dd9cc71dc8830db38cfea9/aten/src/THC/THCCachingAllocator.cpp).

**Comment by maleadt** [comment]
it'd be good to look at that pytorch allocator for other design ideas too.

**Comment by ekinakyurek** [comment]
Definitely, two important ideas there were:

* Different buddy pooling scheme for small and large arrays
* Splitting large arrays for reuse

**Comment by MikeInnes** [comment]
What's nice about the current scheme is that on the happy path, pool lookups are constant time and *really* fast. But the (worst case) 2x memory overhead is a high price to pay for that. Kernel launch times give us a reasonably good time budget to play in terms of doing something smarter.

**Comment by ekinakyurek** [comment]
But this is the easiest solution for memory allocation. If you try to use large batch sizes on gpu demanding models, you will see that PyTorch is faster and uses less memory.

**Comment by denizyuret** [comment]
Ekin and I have been experimenting on Knet. Tried using sqrt(2), exact
match etc.  By far the biggest impact came from taking control of the gc
process -- get your AD to release used outgrad arrays without waiting for
Julia GC.  Cuts memory usage in half.

**Comment by maleadt** [comment]
> By far the biggest impact came from taking control of the gc process -- get your AD to release used outgrad arrays without waiting for Julia GC

Forcing `finalize` on a CuArray should release the memory and make it available for reuse, doing a `gc()` after that would actually free memory. I'm told the former is slow though, so we probably need an API for that (that marks the array as finalized), and similarly calling `gc()` is not guaranteed to sweep the object you care about so would need an alternative (if it ever makes sense to actually free memory, IIUC just releasing it to the pool would be sufficient). Anyway, we can easily add some interface for that to the allocator.

**Comment by denizyuret** [comment]
The problem is to force finalize in a safe manner.  I found out that there
is a lot of pointer sharing on the tape.  For example when you have a
reshape operation, the same GPU pointer is used in multiple nodes on the
tape. My first few implementations failed for this reason.  I have a
bug-free but sub-optimal implementation now.  Since we know everything on
the tape, to prove one of the GPU pointers will no longer effect future
computation should be not too difficult. We have to balance the cost of the
proof with the benefit of early reuse.

**Comment by una-dinosauria** [comment]
> Forcing `finalize` on a CuArray should release the memory and make it available for reuse, doing a `gc()` after that would actually free memory.

I just tried the following on Julia 1.0.1:

```julia
julia> using CuArrays

julia> a = CuArrays.CuArray{Float32}(2);

julia> finalize(a)

julia> GC.gc()

julia> a
2-element CuArray{Float32,1}:
 0.0
 0.0

julia> a
2-element CuArray{Float32,1}:
 0.0
 0.0

[wait 5 seconds or so]

julia> a
2-element CuArray{Float32,1}:
Error showing value of type CuArray{Float32,1}:
ERROR: CUDA error: invalid argument (code #1, ERROR_INVALID_VALUE)
Stacktrace:
 [1] #download!#11(::Bool, ::Function, ::Ptr{Float32}, ::CUDAdrv.Mem.Buffer, ::Int64, ::CUDAdrv.CuStream) at /home/julieta/.julia/packages/CUDAdrv/LC5XS/src/memory.jl:254
 [2] download! at /home/julieta/.julia/packages/CUDAdrv/LC5XS/src/memory.jl:248 [inlined] (repeats 2 times)
 [3] unsafe_copyto! at /home/julieta/.julia/packages/CuArrays/clDeS/src/array.jl:81 [inlined]
[omitted]
 [25] run_main_repl(::Bool, ::Bool, ::Bool, ::Bool, ::Bool) at ./client.jl:330
 [26] exec_options(::Base.JLOptions) at ./client.jl:242
 [27] _start() at ./client.jl:421
```

There seems to be a lag between `gc()` and the memory freeing actually happening.
Is there a way to make this faster? I think this would allow me to free my big arrays in time to avoid running out of memory.

**Comment by MikeInnes** [comment]
My main worry about that approach is that it doesn't seem safe in general; you're assuming all references expire outside of a `grad` context, but in principle an array could escape and it will get freed early. That's of course not common for what Knet is used for, but it can come up if you do nested derivatives etc.

**Comment by denizyuret** [comment]
Here is one way to make it safe for the most common use cases:

1. don't do gcnode for nested derivatives -- which currently are not used
in large scale gpu heavy machine learning models anyway.

2. any intermediate value pointer that was created during the gradient
calculation is safe because it never gets exposed to the user.  More
specifically if an intermediate value was not created based on a pointer
that existed before the gradient calculation and its pointer is not shared
by anything that will be used after the gradient calculation (like
parameter gradients), then it is safe.  As long as grad (or @diff or
whatever) is an atomic operation we can make sure there are no escaped
arrays.

I am not suggesting this is the only/best way to go.  But we need some way
to release memory on the backward pass, so we don't end up using twice as
much memory as everybody else.

**Comment by maleadt** [comment]
> The problem is to force finalize in a safe manner.

We already handle this. If you call `finalize` on a `CuArray`, it'll call `CUDAdrv.release` on the buffer. This is essentially refcounting, once that returns `true` we'll actually free the memory using `CuArrays.dealloc`.

The real problem is that calling `finalize` is expensive. We should just add a field to `CuArray` indicating if the object has been finalized already and allow (cheap) calls to the underlying `unsafe_free!`.

> I think the right idea may be not to rely on GC.gc at all.

I _really_ don't think a fully custom GC is the way forward. We haven't tuned the current allocator at all, so branding it unfixable for GPU workloads seems premature. Fixing the exponential growth and adding some APIs to manage memory should go a long way.

**Comment by denizyuret** [comment]
On Thu, Oct 4, 2018 at 2:35 AM Tim Besard <notifications@github.com> wrote:

> The problem is to force finalize in a safe manner.
>
> We already handle this. If you call finalize on a CuArray, it'll call
> CUDAdrv.release on the buffer. This is essentially refcounting, once that
> returns true we'll actually free the memory using CuArrays.dealloc.
>
Valentin tried to explain to me what kind of refcounting you mean here but
I am still not sure I understand. If the user can choose to put the same
CuArray in 10 different structs in their model, how do we know when we can
safely dealloc (by which I assume you mean not cudaFree but allow reuse,
right?).


>
The real problem is that calling finalize is expensive. We should just add
> a field to CuArray indicating if the object has been finalized already
> and allow (cheap) calls to the underlying unsafe_free!.
>
> I think the right idea may be not to rely on GC.gc at all.
>
> I *really* don't think a fully custom GC is the way forward. We haven't
> tuned the current allocator at all, so branding it unfixable for GPU
> workloads seems premature. Fixing the exponential growth and adding some
> APIs to manage memory should go a long way.
>

I certainly did not mean to declare the current GC unfixable, I don't
understand enough about it: All I know is the GC actions are not under my
control, GC.gc() is expensive, so I need some way to cheaply and safely
call finalizers to fit large models into GPU memory.
