### ISSUE TITLE
Wrapping SVD can not be done at the moment due to restrictive struct definition in Base

### ISSUE THREAD

**Issue by mbeltagy** [JuliaGPU/CuArrays.jl#176]
I was trying to write a convenience function to SVD 
```julia
using CuArrays, CuArrays.CUSOLVER
import LinearAlgebra.svd
function svd(d_A::CuMatrix{T}) where T
    A=collect(d_A)
    d_U, d_S, d_Vt = CUSOLVER.gesvd!('A','A',d_A)
    SVD( d_U, d_S, d_Vt)
end
```
When I ran into a problem... The definition of the SVD struct from https://github.com/JuliaLang/julia/blob/master/stdlib/LinearAlgebra/src/svd.jl will not allow it. 

```julia
# Singular Value Decomposition
struct SVD{T,Tr,M<:AbstractArray{T}} <: Factorization{T}
    U::M
    S::Vector{Tr}
    Vt::M
    function SVD{T,Tr,M}(U, S, Vt) where {T,Tr,M<:AbstractArray{T}}
        @assert !has_offset_axes(U, S, Vt)
        new{T,Tr,M}(U, S, Vt)
    end
end
```

This might work if in the above definition is relaxed to
```
 S::AbstractVector{Tr}
```
It that something worth pursuing upstream in base?

**Comment by andreasnoack** [comment]
Indeed the base version is too restrictive. However, generally it is not a good solution to have fields with abstract types since it operations can no longer be inferred. Instead, it could be made parametric similarly to `M`. For now, we should probably just have a `CuSVD` that mimics the `SVD` struct the same way that we have `CuQR`.
