### ISSUE TITLE
cufunc wrappers of NNlib activation functions

### ISSUE THREAD

**Issue by matsueushi** [JuliaGPU/CuArrays.jl#614]
Hi, 

This is a question about `@cufunc` wrapper functions for NNlib. I found some of [activation functions in NNlib](https://github.com/FluxML/NNlib.jl/blob/master/src/activation.jl) (`σ`, `logσ`, `elu`, `swish`, `gelu`, `selu`, `softplus`) have its wrapper function in [src/nnlib.jl](https://github.com/JuliaGPU/CuArrays.jl/blob/master/src/nnlib.jl) (of CuArrays). 

There have been a lot of changes in NNlib (https://github.com/FluxML/NNlib.jl/pull/149, https://github.com/FluxML/NNlib.jl/pull/145, https://github.com/FluxML/NNlib.jl/pull/162, https://github.com/FluxML/NNlib.jl/pull/168, https://github.com/FluxML/NNlib.jl/pull/170, https://github.com/FluxML/NNlib.jl/pull/175) without changing CuArrays. I'm not quite familier with CuArrays, so please let me ask:

 - Why do we have these wrapper functions?
 - Do we have to add all activation functions available in NNlib to CuArrays?
 
If we need to keep syncing src/nnlib.jl with NNlib, I will update the wrappers and add a comment about CuArrays to NNlib so that everyone can notice.

**Comment by maleadt** [comment]
> Why do we have these wrapper functions?

Some implementations of these functions are incompatible with the GPU, because they use math functions from Base that would dispatch to a CPU implementation (e.g. from OpenLibm). By using `@cufunc`, a GPU-version gets generated where these known-bad intrinsics get rewritten to GPU counterparts from CUDAnative.jl.

> Do we have to add all activation functions available in NNlib to CuArrays?

No, only those that call bad functionality. The implementations generated by `@cufunc` get saved in a list and consulted by certain functions from CuArrays like broadcast and mapreduce. Without such an implementation, the existing definitions from, here, NNlib will be used.

**Comment by matsueushi** [comment]
Thank you so much. So it s enough to update the existing wrappers, right?

**Comment by matsueushi** [comment]
Closing this since https://github.com/JuliaGPU/CuArrays.jl/pull/615 was merged and I added a comment to NNlib https://github.com/FluxML/NNlib.jl/pull/183.
